# Generated by Django 4.2.24 on 2025-09-22 02:04

from django.db import migrations, models
import photos.utils


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', validators=[photos.utils.validate_image_file]),
        ),
    ]
