# Generated by Django 4.2.24 on 2025-09-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-created_at'], name='photo_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['owner', '-created_at'], name='photo_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['is_public', '-created_at'], name='photo_public_created_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['owner', 'is_public'], name='photo_owner_public_idx'),
        ),
    ]
